### ISSUE TITLE
Incomplete dependent keys

### ISSUE THREAD

**Issue by marcoow** [kellyselden/ember-awesome-macros#164]
I just recognized some of the macros use incomplete dependent keys. I looked at the `array.filterBy` macro for example and realized that with this example:

```js
model: Ember.A([
  Ember.Object.create({ val: 1 }),
  Ember.Object.create({ val: 2 })
]),
filterKey: 'val',
number2: filterBy('model', 'filterKey', 2)
```

the `number2` property doesn't update when any of the model's objects' `val` property changes (as the `model.@each.val` dependent key is missing from the CP).

I think in the case of macros like this that take only atomic arguments this should be fixable (might be much harder for macros like `array.filter` where you'd have to inspect the passed function to get the element property that the CP needs to depend on). Having an incomplete implementation like this might lead to hard to track down bugs.

**Comment by kellyselden** [comment]
> Having an incomplete implementation like this might lead to hard to track down bugs

Wow you're right. I don't know how we can get `filter` to recompute in all cases we need it to. I mean, we can cheat and do something like this:

```js
test: filter('array', [
  'keyOnArray',
  'anotherKeyOnArray',
  'keyOnArray.@each.aDeepKey'
], (...args) => {
  // ...
})
```

This looks pretty ugly, and maybe a regular computed would be better for someone at that point.

**Comment by mriska** [comment]
My 2 cents: I wouldn't even expect `filter` to be smart about the contents of the filtering function and include that in the dependent keys. `filterBy` however, should set up a `collection.@each.key` dependent key.

**Comment by marcoow** [comment]
I think for `filter` you'd only be able to auto-detect dependent keys by somehow overriding the `get` method and then when it is called adding the argument as a dependent key to the CP somehow. That seems like it would be overkill at this point though. You could add a `dependsOn` method or so that could allow adding dependent keys to any CP, e.g.:

```js
test: filter('array', [
  'keyOnArray',
  'anotherKeyOnArray'
], (...args) => {
  // ...
}).dependsOn(keyOnArray.@each.aDeepKey)
```

The problem with dynamic dependent keys though is that in my above example

```js
model: Ember.A([
  Ember.Object.create({ val: 1 }),
  Ember.Object.create({ val: 2 })
]),
filterKey: 'val',
number2: filterBy('model', 'filterKey', 2)
```

initially the `number2` CP depends on `model.@each.val` while if `filterKey` changes to `value`, then `number2` would need to depend on `model.@each.value`. The only way I'm aware of to implement this correctly is using observers and `defineProperty` to redefine the CP with the new dependent key every time the property with the dynamic dependent key (in this case `filterKey`) changes.

I only recently wrote [an example for a class based CP](https://github.com/marcoow/templates-and-logic/blob/master/app/computeds/filter-by.js) that basically works the same way as a class based helper. I feel sth. like that might help making these use cases much simpler and could potentially be extracted in a standalone addon.

**Comment by lolmaus** [comment]
Ran into this issue as well. I have a CP like this:

```js
  areAllShorterThanFive_cp: Ember.computed('data.@each.name', function () {
    return this
    	.get('data')
    	.mapBy('name')
    	.every(name => name.length < 5)
  }),  
```

I've assumed it can be rewritten with `ember-awesome-macros` like this:

```js
  areAllShorterThanFive_every_mapBy:
    every(
      mapBy('data', 'name'),
      item => item.get('name').length < 5
    ),
```

But the latter does not recalculate. :(

Here's a demo: https://ember-twiddle.com/0dc43e01f156470d6c427f856963e0f4?openFiles=controllers.application.js%2C

**Comment by kellyselden** [comment]
I hope to get to this fix this weekend.

**Comment by steven-ferguson** [comment]
I think this should also apply to the `getBy` macro. In the example below, if I change the value of `key` to `propB`, I would expect `value1` to update to `'another value'`

```javascript
key: 'propA',
model: {
  propA: 'my value',
  propB: 'another value'
},
value1: getBy('model', 'key'), // 'my value'
```

**Comment by steven-ferguson** [comment]
The `getBy` macro also seems to have an incomplete dependent key list. In the following example, if I update `model.modelProperty`, `value1` does not update.

```javascript
key: 'modelProperty',
model: {
  modelProperty: 'my value'
},
value1: getBy('model', 'key'), // 'my value'
```

**Comment by kellyselden** [comment]
Finally fixed on master!

**Comment by lolmaus** [comment]
You rock! <img src="http://findicons.com/files/icons/422/harry_potter/128/philosopher_s_stone_2.png" width="24" height="24" align="middle">
