### ISSUE TITLE
repo description typo

### ISSUE THREAD

**Issue by JackCA** [kellyselden/ember-awesome-macros#210]
two things:
- the Github repo description currently reads:  `A ollection(sic) of Ember computed macros`
- this library is awesome

**Comment by kellyselden** [comment]
> this library is awesome

Thank you! I guess I named the project correctly then lol

Mind submitting a PR?

**Comment by JackCA** [comment]
@kellyselden I would but I can't because it's part of github, not your source: 

<img width="401" alt="screenshot 2017-01-18 15 05 27" src="https://cloud.githubusercontent.com/assets/296167/22086849/a999b4e4-dd8f-11e6-8798-db3339f9affe.png">

**Comment by kellyselden** [comment]
Oh my bad, I thought you were talking about package.json description. Fixed.
