### ISSUE TITLE
htmlSafe not exported from string index

### ISSUE THREAD

**Issue by JackCA** [kellyselden/ember-awesome-macros#211]
After receiving the deprecation warning about `htmlSafe` moving to `string.htmlSafe` I tried to do the following: `import { htmlSafe} from 'ember-awesome-macros/string'` but it is missing.

it looks like the [string index](https://github.com/kellyselden/ember-awesome-macros/blob/v0.29.0/addon/string/index.js) does not export `htmlSafe`. I would assume it should (as well as a few others that appear to be missing).

If @kellyselden agrees that this is an issue, I can implement the fix for this.

**Comment by kellyselden** [comment]
Ah you're right. I missed it in the mass move refactor to /array, /promise, and /string.

Mind adding is-html-safe.js too while you're at it? I missed those two.
