### ISSUE TITLE
add notEmpty macro

### ISSUE THREAD

**Issue by kellyselden** [kellyselden/ember-awesome-macros#241]

**Comment by Techn1x** [comment]
Also `notEmpty` (since @ember/object/computed has both defined)

https://www.emberjs.com/api/ember/2.16/classes/@ember%2Fobject%2Fcomputed/methods/empty?anchor=empty
https://www.emberjs.com/api/ember/2.16/classes/@ember%2Fobject%2Fcomputed/methods/notEmpty?anchor=notEmpty

**Comment by kellyselden** [comment]
isEmpty is done. Anyone can use it as the basis for a notEmpty macro.

**Comment by mriska** [comment]
isEmpty is implemented in #443 for reference.

**Comment by kellyselden** [comment]
released in v3.1.0
