### ISSUE TITLE
`array.sort` breaks on DS.PromiseArray

### ISSUE THREAD

**Issue by gabrielgrant** [kellyselden/ember-awesome-macros#249]
Fails on [this line](https://github.com/kellyselden/ember-awesome-macros/blob/master/addon/array/sort.js#L41), complaining `Uncaught TypeError: array.sort is not a function`

Indeed, [`Ember.ArrayProxy`](http://emberjs.com/api/classes/Ember.ArrayProxy.html) doesn't seem to implement a `sort` method (which I guess makes sense, since it's not entirely clear what it should do)

The official `Ember.computed.sort()` [does a `slice()` to copy the array before sorting](https://github.com/emberjs/ember.js/blob/v2.11.0/packages/ember-runtime/lib/computed/reduce_computed_macros.js#L732)

I haven't delved into the `ember-awesome-macros` code far enough to see where the parameter passed into `ember-awesome-macros/array.sort()` originates, but it seems like doing the same `slice()`-to-copy should fix this issue (and probably avoid others -- right now the original array is being mutated when the sort macro is accessed, which I certainly found unexpected)

**Comment by kellyselden** [comment]
Regarding the array promise, you should be able to wrap it in a [promiseArray](https://github.com/kellyselden/ember-awesome-macros#promisearray) first.

As for mutating the array, definitely a bug.

**Comment by gabrielgrant** [comment]
Pretty sure anything wrapped with `promiseArray` will have the same problem as the [`DS.PromiseArray`](http://emberjs.com/api/data/classes/DS.PromiseArray.html) -- because both are based on [`Ember.ArrayProxy` which doesn't implement a `sort()` method](http://emberjs.com/api/classes/Ember.ArrayProxy.html), right?

**Comment by kellyselden** [comment]
@gabrielgrant You're probably right.
