### ISSUE TITLE
Pleeeeease add a changelog

### ISSUE THREAD

**Issue by Turbo87** [kellyselden/ember-awesome-macros#253]
otherwise it's really hard to figure out what the breaking changes are between each version... 😭

**Comment by kellyselden** [comment]
You're gonna make me install ruby aren't you! 😄
I'm on it.

**Comment by Turbo87** [comment]
feel free to do it manually or use another tool, but pleeeeease so *something*! 😉

**Comment by kellyselden** [comment]
Resolved by #254
