### ISSUE TITLE
eq('key', 0) doesn't seem to work

### ISSUE THREAD

**Issue by Turbo87** [kellyselden/ember-awesome-macros#322]
even if `key` equals `0` I'm seeing it as `false`... 🤔

**Comment by kellyselden** [comment]
What the heck. How are my tests passing I wonder.

**Comment by Turbo87** [comment]
might be related to `0` being falsy? haven't investigated further yet. https://github.com/skylines-project/skylines/pull/643/commits/bc878696d6b77e915f63336c981584a7b96f533e fixed it for now.

**Comment by kellyselden** [comment]
#325 fixed it. Noob mistake hasOwnProperty.

**Comment by Turbo87** [comment]
Awesome, thanks!
