### ISSUE TITLE
array.filterBy error in 0.35.3

### ISSUE THREAD

**Issue by crhayes** [kellyselden/ember-awesome-macros#330]
![image](https://cloud.githubusercontent.com/assets/727536/25760778/533b7662-31a6-11e7-93e0-9ae717dd6e56.png)

I've reproduced the error here:

https://ember-twiddle.com/d7dd5effe57ceb8b1c2153009b671032

You can see the error in the console.

**Comment by kellyselden** [comment]
This should be fixed in ember-macro-helpers v0.14.1. It is in range, so all you have to do is reinstall node modules. Please reopen if it is still an issue.

**Comment by crhayes** [comment]
@kellyselden Thanks!
