### ISSUE TITLE
Composing array macros from promise properties

### ISSUE THREAD

**Issue by mwpastore** [kellyselden/ember-awesome-macros#336]
I'd like to understand why this works:

```javascript
totalCost: sum(computed('units.@each.cost', _ => _.mapBy('cost')))
```

But this doesn't:

```javascript
totalCost: sum(array.mapBy('units', 'cost'))
```

(It fails with "Maximum call stack size exceeded" on Ember 2.13 and 2.14-beta.)

Where `totalCost` is a computed property on a DS.Model that hasMany `units` (async), and the `unit` DS.Model has a normal attribute named `cost`. 

Thanks in advance, and thank you for this awesome add-on (and ember-macro-helpers as well)!

**Comment by mwpastore** [comment]
Hrrm, array.mapBy seems wonky on 2.14-beta altogether, e.g. `array.mapBy('units', 'cost')` is returning an array of units, not an array of costs as expected.

**Comment by mwpastore** [comment]
Oh lordy, I'm missing `raw()`'s all over the place. Please disregard and my apologies for the noise!

**Comment by kellyselden** [comment]
Sorry that tripped you up. I'm open to ideas on how to provide feedback when someone makes this mistake.

**Comment by mwpastore** [comment]
That's okay. Chalk it up to a learning curve. I'm not sure there's a way to warn the caller without breaking other behavior.
