### ISSUE TITLE
Missing Dependent Keys

### ISSUE THREAD

**Issue by offirgolan** [kellyselden/ember-awesome-macros#338]
First of all, I just wanted to say well done with this addon! 

I have been playing around with this repo that last couple of days and found that there are a good amount of macros that do not have the correct dependents specified. Im not really sure if this has to do directly with ember-macro-helpers or just how this repo is parsing everything. 

### Object: `getBy`

```js
myObj: { foo: 'bar' },
someProp: 'foo',
getBy('myObj', 'someProp')
```
This only adds `myObj` and `someProp` as the dependents but it should actually be `myObj.someProp`.  

### Array Macros

All (at least the ones I've used) of the array macros do not include the necessary dependents to recompute. 

filterBy, mapBy, isAny, isEvery, etc do not include `array.@each.key` and the rest do not include `array.[]`. They only seem to include `array` and `key` if present but that is not correct. 

To get around that, you have to create intermediate properties which I think can be easily avoided if the necessary dependent keys are added. 

### Environment

Ember-CLI: 2.12
Ember: 2.12
Ember-Awesome-Macros: 0.36.0
Ember-Macro-Helpers: 0.14.1

**Comment by kellyselden** [comment]
The array macros should work the way you want. Have you tried? getBy is missing that capability though. I missed it when adding it to the array macros.

**Comment by kellyselden** [comment]
If you want, you could update getBy to add this capability by using https://github.com/kellyselden/ember-awesome-macros/pull/252 as a guide. Otherwise, I'll get to it when I get some more free time.

**Comment by offirgolan** [comment]
@kellyselden I can wait for the `getBy` stuff. Im just using `defineProperty` in the meantime as it does practically the same thing. 

As for the array dependents, here is a twiddle to show you what I mean:

https://ember-twiddle.com/42272f8f43f85483854b9a5144d32b4f?openFiles=controllers.application.js%2C

The dependentKeys are `array, prop` where it needs to be `array.@each.prop`. This is a common problem across all array macros. 

Macros that dont need a specified property should have `array.[]` added as dependents or they will not be recomputed when a new item is added/removed.

**Comment by offirgolan** [comment]
Either that... or Im missing something here lol

**Comment by offirgolan** [comment]
@kellyselden it looks like this issue arises when using `computed` + `awesome macro`

[See Twiddle](https://ember-twiddle.com/42272f8f43f85483854b9a5144d32b4f?openFiles=controllers.application.js%2C)

**Comment by kellyselden** [comment]
Yea a macro that uses `createClassComputed` inside another computed had an issue that I fixed a few minutes ago in #337. If you change that twiddle to:

    "ember-awesome-macros": "0.36.1",
    "ember-macro-helpers": "0.15.0"

It should work.

**Comment by offirgolan** [comment]
@kellyselden thats awesome. I will test it in my app tomorrow and follow up. Thanks for the quick fixes 😄

**Comment by HeroicEric** [comment]
The array macros still seem to not be working https://ember-twiddle.com/e215126d6211cd13703e71156231b800?openFiles=controllers.application.js%2C

**Comment by offirgolan** [comment]
@kellyselden feel free to close this issue once `getBy` has been fixed 😄 

Thanks again for all the hard work!
