### ISSUE TITLE
sum doesn't accept an array

### ISSUE THREAD

**Issue by mwpastore** [kellyselden/ember-awesome-macros#341]
It would be nice if `sum` accepted an array:

```javascript
array: Ember.A([{ test: 1 }, { test: 2 }]),
key: 'test',
value: sum(array.mapBy('array', 'key')) // expected: 3
```

But this does not work because `sum` expects stringy property keys, not an array.

**Comment by kellyselden** [comment]
`reduce` would normally be used to accomplish this

```js
array: Ember.A([{ test: 1 }, { test: 2 }]),
key: 'test',
value: reduce(mapBy('array', 'key'), (sum, i) => sum + i, 0)
```

I'm on the fence if `sum` should be that complex, although https://www.emberjs.com/api/classes/Ember.computed.html#method_sum only takes arrays...

**Comment by mwpastore** [comment]
I'll admit that it's a little greedy of me to want this. 😄 How about a new `array.sum` macro?

**Comment by kellyselden** [comment]
I just had a need for this, so I may implement soon.
