### ISSUE TITLE
Failing test using macro that depends on relationship property

### ISSUE THREAD

**Issue by Fed03** [kellyselden/ember-awesome-macros#344]
I'm trying to unit test a computed property on an Ember.Controller obj. The property depends on a `hasMany`relationships defined on the model (like `model.posts`)

The error is raised after the assert phase, likely during the teardown phase. 
The error is:
`Error: Assertion Failed: Cannot call writeDeps after the object is destroyed.`

I've created a repo with the bare minimum showing the error https://github.com/Fed03/ember-macro-test

Let me know if and how I can help, ty

**Comment by kellyselden** [comment]
This should be fixed in ember-macro-helpers v0.15.1.
