### ISSUE TITLE
filterBy and rejectBy without value operand

### ISSUE THREAD

**Issue by buschtoens** [kellyselden/ember-awesome-macros#362]
`Ember.Enumerable.filterBy` and `Ember.Enumerable.rejectBy` leave the value that is compared against optional. If no value is provided, they check for truthiness.

As far as I can see the `filterBy` and `rejectBy` macros differ from that and require a third parameter to be passed.

Can this be made optional as well? I'm up for a PR! :slightly_smiling_face:

**Comment by kellyselden** [comment]
Thanks for the issue, and yes a PR would be awesome!

**Comment by kellyselden** [comment]
Resolved in #364
