### ISSUE TITLE
_emberAwesomeMacros.string.trim is not a function

### ISSUE THREAD

**Issue by alexmiddeleer** [kellyselden/ember-awesome-macros#437]
Hey there - thanks for the addon! I'm using the latest tagged version, but it looks like the trim function is still not available yet. Edit: tried master - same issue. If I switch `trim` to any other string function it works (e.g. dasherize).

**Comment by ctjhoa** [comment]
I've just run some test with `ember@2.4.6` & `ember-awesome-macros@0.41.0` and trim work as expected for me.
Can you double check your `ember-awesome-macros` version? (I can reproduce your issue with version `0.40.0`)
What's your ember version?

**Comment by ctjhoa** [comment]
I import `trim` like this
```js
import { trim } from 'ember-awesome-macros/string';
```

**Comment by alexmiddeleer** [comment]
I think I found the problem. One of our addons had ember-awesome-macros as a dependency `^.0.41.0`. Our app had the devDependency `*^.0.41.0`. I am not sure if it's ember's fault or yarn's, but everything worked when we upgraded the addon's version.

**Comment by alexmiddeleer** [comment]
I asked about this in the ember help channel and it seems to just be ember-cli quirk where ember-cli can't really make a good decision about which dependency should win. But it's almost 100% not an ember-awesome-macros issue.
