### ISSUE TITLE
`isAny` not working for Ember Data arrays

### ISSUE THREAD

**Issue by Turbo87** [kellyselden/ember-awesome-macros#441]
```js
export default Model.extend({
  users: hasMany('user', { inverse: 'group', async: false }),

  hasAdmins: isAny('users', raw('role'), raw('admin')),
});
```

I would assume that this works, but it seems that the `isAny()` is not quite working correctly for some reason. It seems to go into [this](https://github.com/kellyselden/ember-awesome-macros/blob/master/addon/array/-utils.js#L78-L79) code path since it is neither an array, not an `ArrayProxy`.

**Comment by lolmaus** [comment]
Duplicate of #423?

**Comment by Turbo87** [comment]
apparently, yeah 🙈
