### ISSUE TITLE
add array `sortBy`

### ISSUE THREAD

**Issue by kellyselden** [kellyselden/ember-awesome-macros#447]

**Comment by baljeet03** [comment]
Can I raise a PR for this? Or someone is working on it.

**Comment by kellyselden** [comment]
Feel free, no one is working on it.

**Comment by mum-never-proud** [comment]
Hey @kellyselden I wanna raise a pr for this, I wanna know a thing the `sortBy` should support `asc` and `desc` 

if yes we can make use of current sort implementation correct?

I guess we are just doing sugar coat on the sort

let me know your thoughts on this

thanks

**Comment by mum-never-proud** [comment]
@kellyselden ~~pong~~ can you please review this, as I am in need of this implementation
