### ISSUE TITLE
Deprecation warning under Ember 2.18

### ISSUE THREAD

**Issue by bartocc** [kellyselden/ember-awesome-macros#452]
ember-string-ishtmlsafe-polyfill@2.0.0 is the latest version to date and causes a deprecation warning under ember 2.18 because of its hard dependency on "ember-cli-version-checker": "^1.2.0".

Do we really need a hard dependency on ember-string-ishtmlsafe-polyfill in ember-awesome-macros?

**Comment by bartocc** [comment]
Seems ember ~1.13.0 is tested in ember-try.js, which would justify the need for ember-string-ishtmlsafe-polyfill.

The next ember version tested in ember-try.js is ember-lts-2.12, and for this one and above, ember-string-ishtmlsafe-polyfill should be useless.

Could we release a 0.50.0 without ember-string-ishtmlsafe-polyfill and a 0.42.0 with it to maintain compatibility with ember ~1.13.0? Would that be semver compliant?

**Comment by kellyselden** [comment]
That should not be the reason to drop ember 1.13 support. You should file an issue on ember-string-ishtmlsafe-polyfill to bump their version of ember-cli-version-checker.

**Comment by bartocc** [comment]
Actually, there is already an issue https://github.com/workmanw/ember-string-ishtmlsafe-polyfill/issues/8 and a PR https://github.com/workmanw/ember-string-ishtmlsafe-polyfill/pull/7 but no feedback has been provided yet…

**Comment by bartocc** [comment]
A new version of ember-string-ishtmlsafe-polyfill has been released that fixes this issue

https://github.com/workmanw/ember-string-ishtmlsafe-polyfill/issues/11#event-1556335087

Do you want a PR to update the dependency on it?

**Comment by kellyselden** [comment]
Yes please

**Comment by bartocc** [comment]
ember-awesome-macros already depends on `"ember-string-ishtmlsafe-polyfill": "^2.0.0"` which is semver compliant with `ember-string-ishtmlsafe-polyfill@2.0.1`.

`ember install ember-awesome-macros` in a project right now would then fetch `ember-string-ishtmlsafe-polyfill@2.0.1` and there would be no deprecation warning.

I am starting to wonder if what's missing to ember-awesome-macros is not a `yarn.lock` or `package-lock.json`.

Would you be willing to add such a file ?

**Comment by kellyselden** [comment]
lockfiles only involve this project, not consumers. There is nothing left to fix. People just need to update their own lockfiles.
