### ISSUE TITLE
findBy returns array

### ISSUE THREAD

**Issue by H1D** [kellyselden/ember-awesome-macros#475]
`findBy` returns an array instead of found item as it [should](https://emberjs.com/api/ember/2.15/classes/Ember.Array/methods/findBy?anchor=findBy)

Docs [said](https://github.com/kellyselden/ember-awesome-macros#arrayfindby) that it just wraps `Ember.Array.findBy` but it works more like `filterBy`

Here is twiddle:
https://ember-twiddle.com/ba47504b322f2e6339f53206a0110627?openFiles=controllers.application.js%2C

**Comment by kellyselden** [comment]
You're not escaping your string properly `firstElem: findBy('array',raw('key'),1)`
