### ISSUE TITLE
array.findBy returning an array?

### ISSUE THREAD

**Issue by jfrux** [kellyselden/ember-awesome-macros#520]
I've tested it and I can't seem to get `array.findBy` to return the true value that is being returned from Ember.Array.findBy

```
...
myArray: computed(..., function() {
  return [{
         "name": "Object 1",
         "isActive": true
   },{
         "name": "Object 2",
         "isActive": false
   },{
         "name": "Object 3",
         "isActive": false
   }];
}),
activeRow: array.findBy('myArray','isActive',true) // returns [ {...}, {...}, {...} ]
...
```

Meanwhile...
```
myObject.get('myArray').findBy('isActive') // returns {...}
```

**Comment by jfrux** [comment]
Having to use something like this to get around it which obviously is overkill but works...

```
activeRow: array.first(array.filterBy('myArray','isActive'))
```

**Comment by jfrux** [comment]
Spoke too soon!
Actually, `array.filterBy('myArray','isActive')` does not filter either.. it just returns full array.
Interesting...

**Comment by jfrux** [comment]
My bad, thank you!

**Comment by mriska** [comment]
@jfrux, no problem. I have made the same mistake myself and so have several of my colleagues. You are in good and plentiful company here :)

**Comment by kellyselden** [comment]
Thanks @mriska!
