### ISSUE TITLE
Add innerText macro

### ISSUE THREAD

**Issue by candunaj** [kellyselden/ember-awesome-macros#533]
Hi,
It would be useful to have innerText macro. Then I could validate html input and check whether there is some text.
isHtmlValid: notEmpty(string.trim(innerText('htmlProperty')));

It could be implemented like this:
function innerText(property){
	return computed(property, function(){
		var span = document.createElement('div');
		span.innerHTML = this.get(property);
		return span.textContent || span.innerText;
	});
}

Thank you

**Comment by kellyselden** [comment]
Thanks for the suggestion. That seems like a special case macro that you could implement in your own project via https://github.com/kellyselden/ember-macro-helpers#custom-macros. I don't think it's a good candidate for this repo.
