### ISSUE TITLE
raw() is screwed up on ember-canary

### ISSUE THREAD

**Issue by markcharyk** [kellyselden/ember-awesome-macros#546]
When running ember-canary, `raw` throws the error message:
```
Uncaught Error: Assertion Failed: Brace expanded properties cannot contain spaces, e.g. "user.{firstName, lastName}" should be "user.{firstName,lastName}"
```

The particular message doesn't have anything to do with the error except to indicate that `raw` is trying to key-ify something that meant to be key-ified.

By way of repro, I made [this codesandbox](https://codesandbox.io/s/github/markcharyk/raw-canary/tree/master/). You can see the template not render correctly and can see the error if you open up the DevTools.

**Comment by kellyselden** [comment]
Here is the issue I filed to track this https://github.com/emberjs/ember.js/issues/17641. I don't know when I'll have the time to dig in.

**Comment by kellyselden** [comment]
Should be fixed now.
